// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBze6dpRcuLLuzdeXEnzt1SUFyX7sghLqY',
    appId: '1:293241315575:web:179e03a7f4e6debddbb3f2',
    messagingSenderId: '293241315575',
    projectId: 'bcs-backend-e4ac3',
    authDomain: 'bcs-backend-e4ac3.firebaseapp.com',
    storageBucket: 'bcs-backend-e4ac3.appspot.com',
    measurementId: 'G-B5CP8ZESK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ZX-1LVDpUbT94qL87Y5sZDlW3LoMug0',
    appId: '1:293241315575:android:5aaf3ba8e51c97dcdbb3f2',
    messagingSenderId: '293241315575',
    projectId: 'bcs-backend-e4ac3',
    storageBucket: 'bcs-backend-e4ac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4f1QZDVE1NU1hviDF1UoFC4doFWu4x4',
    appId: '1:293241315575:ios:f82fde4f11d60361dbb3f2',
    messagingSenderId: '293241315575',
    projectId: 'bcs-backend-e4ac3',
    storageBucket: 'bcs-backend-e4ac3.appspot.com',
    iosBundleId: 'com.example.belisoncentralschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBze6dpRcuLLuzdeXEnzt1SUFyX7sghLqY',
    appId: '1:293241315575:web:aff1413bcc8866e2dbb3f2',
    messagingSenderId: '293241315575',
    projectId: 'bcs-backend-e4ac3',
    authDomain: 'bcs-backend-e4ac3.firebaseapp.com',
    storageBucket: 'bcs-backend-e4ac3.appspot.com',
    measurementId: 'G-MVMJ4CJDYC',
  );

}